# yaml-language-server: $schema=false

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=instock
      - JWT_SECRET=supersecretkey
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_SECURE=false
      - EMAIL_USER=shammahhirwa19@gmail.com
      - EMAIL_PASS=zmsh owkx vipq otru
      - FRONTEND_URL=https://instock-inventory-pro.vercel.app/
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
    depends_on:
      - db
    networks:
      - instock-network

  db:
    image: postgres:15-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=instock
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - instock-network

networks:
  instock-network:
    driver: bridge

volumes:
  postgres_data:
